# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shigalle-predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PIL import Image
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEventLoop, QTimer
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QWidget
import visual_curve
import CNN_predict
import matplotlib.pyplot as plt


class EmittingStr(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str)

    def write(self, text):
        self.textWritten.emit(str(text))
        loop = QEventLoop()
        QTimer.singleShot(1000, loop.quit)
        loop.exec_()

    def flush(self):  # real signature unknown; restored from __doc__
        """ flush(self) """
        pass

class MyQLabel(QtWidgets.QLabel):
    button_clicked_signal = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(MyQLabel, self).__init__(parent)

    def mouseReleaseEvent(self, QMouseEvent):
        self.button_clicked_signal.emit()

    def connect_customized_slot(self, func):
        self.button_clicked_signal.connect(func)


########################################################################################################################
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1751, 1048)
        Form.setMinimumSize(QtCore.QSize(416, 278))
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("*{background-color: rgba(255, 255, 255, 255);\n"
"    border:3px solid rgba(0, 0, 0, 255);;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(30)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 3, -1, 3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_setting = QtWidgets.QFrame(self.frame)
        self.frame_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_setting.setObjectName("frame_setting")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_setting)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_icon = QtWidgets.QLabel(self.frame_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon.sizePolicy().hasHeightForWidth())
        self.label_icon.setSizePolicy(sizePolicy)
        self.label_icon.setStyleSheet("border:0px;")
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap("item.png"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")
        self.verticalLayout_2.addWidget(self.label_icon)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_setting)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 5, 3, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_file = QtWidgets.QLineEdit(self.frame_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_file.sizePolicy().hasHeightForWidth())
        self.lineEdit_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_file.setFont(font)
        self.lineEdit_file.setText("")
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.verticalLayout.addWidget(self.lineEdit_file)
        self.pushButton_open = QtWidgets.QPushButton(self.frame_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open.sizePolicy().hasHeightForWidth())
        self.pushButton_open.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    background-color: rgb(198, 255, 228);\n"
"    border-radius: 5px;    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: rgb(43, 255, 138);\n"
"}\n"
"QPushButton:pressed, QPushButton:checked {    \n"
"    border: 0px;\n"
"    background-color: rgb(43, 255, 138);    \n"
"}\n"
"")
        self.pushButton_open.setCheckable(False)
        self.pushButton_open.setChecked(False)
        self.pushButton_open.setAutoExclusive(False)
        self.pushButton_open.setFlat(False)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)
        self.pushButton_RUN = QtWidgets.QPushButton(self.frame_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RUN.sizePolicy().hasHeightForWidth())
        self.pushButton_RUN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.pushButton_RUN.setFont(font)
        self.pushButton_RUN.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    background-color: rgb(211, 248, 255);\n"
"    border-radius: 5px;    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 0px;\n"
"    background-color: rgb(76, 171, 255);\n"
"}\n"
"QPushButton:pressed, QPushButton:checked {    \n"
"    border: 0px;\n"
"    background-color: rgb(76, 171, 255);    \n"
"}\n"
"")
        self.pushButton_RUN.setFlat(False)
        self.pushButton_RUN.setObjectName("pushButton_RUN")
        self.verticalLayout.addWidget(self.pushButton_RUN)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 60)
        self.verticalLayout.setStretch(2, 60)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.setStretch(0, 300)
        self.verticalLayout_6.setStretch(1, 1113)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_setting)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_picture = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_picture.sizePolicy().hasHeightForWidth())
        self.label_picture.setSizePolicy(sizePolicy)
        self.label_picture.setStyleSheet("border: 0px solid rgba(0, 0, 0, 255);")
        self.label_picture.setText("")
        self.label_picture.setScaledContents(True)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_4.addWidget(self.label_picture)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(800000, 2))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setStyleSheet("border: 2px solid rgba(0, 0, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_4.setStretch(0, 341)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.textEdit_result = QtWidgets.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_result.setFont(font)
        self.textEdit_result.setStyleSheet("border: 0px solid rgba(0, 0, 0, 255);")
        self.textEdit_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_result.setLineWidth(0)
        self.textEdit_result.setMidLineWidth(0)
        self.textEdit_result.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_result.setCursorWidth(0)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout_5.addWidget(self.textEdit_result)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border:0px;\n"
"color:grey;\n"
"alignment:right")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_5.setStretch(0, 343)
        self.verticalLayout_5.setStretch(1, 186)
        self.verticalLayout_5.setStretch(2, 31)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 13)
        self.horizontalLayout.setStretch(1, 50)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Acinettobacter Baumannii"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.lineEdit_file.setPlaceholderText(_translate("Form", "Input File (.csv)"))
        self.pushButton_open.setText(_translate("Form", "OPEN"))
        self.pushButton_RUN.setText(_translate("Form", "RUN"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\">Produced by Neural Network  </p></body></html>"))


########################################################################################################################

        self.pushButton_open.clicked.connect(self.get_save)
        self.pushButton_open.clicked.connect(self.call_vsraw)
        self.pushButton_RUN.clicked.connect(self.load_CNN)

########################################################################################################################

    def outputWritten(self, text):
        # self.textEdit.clear()
        cursor = self.textEdit_result.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.textEdit_result.setTextCursor(cursor)
        self.textEdit_result.ensureCursorVisible()

    def get_save(self):
        self.filename, _ = QFileDialog.getOpenFileName(None, 'Single File', '.', '*.csv')
        if self.filename == '':
            pass
        else:
            self.lineEdit_file.setText(self.filename)
            self.filename1 = self.lineEdit_file.text()
            if len(self.filename1) != 0:
                sys.stdout = EmittingStr(textWritten=self.outputWritten)
                sys.stderr = EmittingStr(textWritten=self.outputWritten)

    def call_vsraw(self):
        if self.filename == '':
            pass
        else:
            self.label_picture.clear()
            visual_curve.vsraw(self.filename)
            self.label_picture.setPixmap(QtGui.QPixmap('raw.png'))


    def load_CNN(self):
        if self.lineEdit_file.text() == '':
            pass
        else:
            self.textEdit_result.setReadOnly(True)
            self.textEdit_result.setReadOnly(True)
            self.textEdit_result.clear()
            CNN_predict.CNN_pre(self.filename1)


if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    MainWindow = QWidget()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
